name: hello-world

on: push

jobs: # there could be more than one jobs
  hello-world-job:

    runs-on: ubuntu-latest

    steps:
      - name: check out repository
        uses: actions/checkout@v4
      - run: echo "$(cat hello_world.txt)"
